---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Copy backend files
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu/
    tar xzvf artifact.tar.gz
    cd backend
    npm install
    npm run build
    pm2 start npm -- start